INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (1, null, null, 1, 'Olimjon', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (2, null, null, 1, 'Tursunboy', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (3, null, null, 1, 'Xusanboy', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (4, null, null, 1, 'Saidbek', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (5, null, null, 1, 'Kamola', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (6, null, null, 1, 'Maxpora', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (7, null, null, 1, 'Zuxra', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (8, null, null, 1, 'Muxlisa', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (9, null, null, 0.8, 'Xusniddin', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (10, null, null, 0.8, 'Umidjon', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (11, null, null, 0.8, 'Abdunosir', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (12, null, null, 0.8, 'Sardor', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (13, null, null, 0.8, 'Nazira', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (14, null, null, 0.8, 'Umida', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (15, null, null, 0.8, 'Zilola', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (16, null, null, 0.8, 'Muqaddas opa', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (17, null, null, 0.7, 'Xasanboy', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (18, null, null, 0.7, 'Oltinoy', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (19, null, null, 0.7, 'Dildora', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (20, null, null, 0.7, 'Mumtoza', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (21, null, null, 0.7, 'Nodira opa', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (22, null, null, 0.7, 'Odina', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (23, null, null, 0.7, 'O''g''iloy', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (24, null, null, 0.6, 'Xamida', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (25, null, null, 0.6, 'Nodira 2', 0, '(kichik)');
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (26, null, null, 0.6, 'Nargiza opa 1', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (27, null, null, 0.6, 'Nargiza 2', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (28, null, null, 0.6, 'Mukarramoy', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (29, null, null, 0.5, 'Arabboy', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (30, null, null, 0.5, 'Sanjar', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (31, null, null, 0.5, 'Islombek', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (32, null, null, 0.5, 'Boburjon', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (33, null, null, 0.5, 'Oyqiz', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (34, null, null, 0.5, 'Gulxumor', 0, null);
INSERT INTO public.db_employees (id, created_at, updated_at, experience, first_name, group_id, second_name) VALUES (35, null, null, 0.5, 'Mubina', 0, null);
